//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeocaPreincripcionesAfiliados.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeocaPreinscripcionesEntities2 : DbContext
    {
        public SeocaPreinscripcionesEntities2()
            : base("name=SeocaPreinscripcionesEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afiliados_Familiares> Afiliados_Familiares { get; set; }
        public virtual DbSet<General_Calificacion> General_Calificacion { get; set; }
        public virtual DbSet<General_Delegacion> General_Delegacion { get; set; }
        public virtual DbSet<General_Documentos> General_Documentos { get; set; }
        public virtual DbSet<General_Estado_Civil> General_Estado_Civil { get; set; }
        public virtual DbSet<General_Localidades> General_Localidades { get; set; }
        public virtual DbSet<General_Parentesco> General_Parentesco { get; set; }
        public virtual DbSet<General_Provincias> General_Provincias { get; set; }
        public virtual DbSet<General_Nacionalidades> General_Nacionalidades { get; set; }
        public virtual DbSet<General_Sexo> General_Sexo { get; set; }
        public virtual DbSet<Afiliados_DatosPersonales> Afiliados_DatosPersonales { get; set; }
        public virtual DbSet<Afiliados_Empresa> Afiliados_Empresa { get; set; }
    }
}
