//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeocaPreincripcionesAfiliados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secretaria_Afiliados_Familiares
    {
        public int Codigo { get; set; }
        public Nullable<int> Afiliado { get; set; }
        public Nullable<int> Tipo { get; set; }
        public string ApellidoNombre { get; set; }
        public Nullable<int> TipoDocumento { get; set; }
        public Nullable<int> NroDocumento { get; set; }
        public Nullable<int> Sexo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public Nullable<System.DateTime> Estudio { get; set; }
        public Nullable<bool> Marca { get; set; }
    }
}
