//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeocaPreincripcionesAfiliados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secretaria_Empresas_DDJJ
    {
        public int Id { get; set; }
        public Nullable<int> Empresa { get; set; }
        public string Cuil { get; set; }
        public Nullable<bool> Aporte1 { get; set; }
        public Nullable<bool> Aporte2 { get; set; }
        public Nullable<bool> Aporte3 { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<decimal> Sueldo { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<int> Sucursal { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public Nullable<int> Fuente { get; set; }
        public Nullable<System.DateTime> FechaDatos { get; set; }
        public Nullable<int> Horas { get; set; }
        public Nullable<bool> CuotaAfiliado { get; set; }
    }
}
