//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeocaPreincripcionesAfiliados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secretaria_Empresas
    {
        public int Codigo { get; set; }
        public string Cuit { get; set; }
        public string RazonSocial { get; set; }
        public string NombreFantasia { get; set; }
        public Nullable<int> Zona { get; set; }
        public string CalleFiscal { get; set; }
        public string NroFiscal { get; set; }
        public string LocalidadFiscal { get; set; }
        public string PisoFiscal { get; set; }
        public string DepartamentoFiscal { get; set; }
        public string CPFiscal { get; set; }
        public string TelefonoFiscal { get; set; }
        public string CalleReal { get; set; }
        public Nullable<int> NroReal { get; set; }
        public string LocalidadReal { get; set; }
        public string PisoReal { get; set; }
        public string DepartamentoReal { get; set; }
        public string CPReal { get; set; }
        public string TelefonoReal { get; set; }
        public Nullable<bool> Ubicada { get; set; }
        public Nullable<int> Actividad { get; set; }
        public Nullable<bool> Doc_Habilitacion { get; set; }
        public Nullable<bool> Doc_Contrato_Estatuto { get; set; }
        public Nullable<bool> Doc_DNRP_Inscripcion { get; set; }
        public Nullable<bool> Doc_DNRHE { get; set; }
        public Nullable<bool> Doc_Sueldo { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaInscripcion { get; set; }
        public Nullable<System.DateTime> FechaDeuda { get; set; }
        public string Web { get; set; }
        public string Email { get; set; }
        public string Detalle { get; set; }
        public Nullable<System.DateTime> FechaDatos { get; set; }
        public Nullable<System.DateTime> DDJJ { get; set; }
        public string ContadorNombre { get; set; }
        public string ContadorDomicilio { get; set; }
        public string ContadorLocalidad { get; set; }
        public string ContadorTelefono { get; set; }
        public string ContadorEmail { get; set; }
        public string Observaciones { get; set; }
    }
}
