//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeocaPreincripcionesAfiliados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secretaria_Afiliados
    {
        public int Codigo { get; set; }
        public string ApellidoNombre { get; set; }
        public string Cuil { get; set; }
        public Nullable<int> TipoDocumento { get; set; }
        public string NroDocumento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> Nacionalidad { get; set; }
        public Nullable<int> Sexo { get; set; }
        public Nullable<int> EstadoCivil { get; set; }
        public string Calle { get; set; }
        public string Nro { get; set; }
        public string Piso { get; set; }
        public string Departamento { get; set; }
        public Nullable<int> CodigoPostal { get; set; }
        public Nullable<int> Provincia { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> Delegacion { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<int> TipoCarnet { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public Nullable<bool> Requisito_ReciboSueldo { get; set; }
        public Nullable<bool> Requisito_Matrimonio { get; set; }
        public Nullable<bool> Requisito_PartidaHijos { get; set; }
        public Nullable<bool> Requisito_Dni { get; set; }
        public Nullable<bool> Requisito_OSECAC { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<System.DateTime> FechaNotificacion { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public Nullable<bool> TramiteCumplido { get; set; }
        public string Obs_Generales { get; set; }
        public string Obs_Credencial { get; set; }
        public Nullable<bool> Marca { get; set; }
        public Nullable<System.DateTime> FechaBajaFuturo { get; set; }
        public Nullable<bool> Marca2 { get; set; }
        public string UsuarioC { get; set; }
        public string UsuarioM { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Sucursal { get; set; }
        public Nullable<System.DateTime> FechaIngresoEmpresa { get; set; }
        public Nullable<System.DateTime> UltimoPago { get; set; }
        public Nullable<System.DateTime> AporteDesde { get; set; }
        public Nullable<System.DateTime> AporteHasta { get; set; }
        public Nullable<bool> Aporte1 { get; set; }
        public Nullable<bool> Aporte2 { get; set; }
        public Nullable<bool> Aporte3 { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
        public Nullable<bool> CuotaAfiliado { get; set; }
        public string OrigenDelegacion { get; set; }
        public string OrigenUsuario { get; set; }
        public Nullable<bool> DatosActualizados { get; set; }
    }
}
